import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useQualificationQueueStyles = makeStyles({
  page: {
    minHeight: '100vh',
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground2,
    backgroundImage: `linear-gradient(135deg, ${tokens.colorNeutralBackground1} 0%, transparent 48%)`,
  },
  masthead: {
    minHeight: '68px',
    paddingLeft: '5vw',
    paddingRight: '5vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  brand: { display: 'flex', alignItems: 'center', columnGap: tokens.spacingHorizontalM },
  brandMark: {
    width: '38px',
    height: '38px',
    display: 'grid',
    placeItems: 'center',
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorBrandBackground,
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    fontWeight: tokens.fontWeightSemibold,
  },
  intro: {
    padding: `52px 5vw ${tokens.spacingVerticalXXL}`,
    display: 'flex',
    alignItems: 'end',
    justifyContent: 'space-between',
    gap: tokens.spacingHorizontalXXL,
    '@media (max-width: 820px)': { alignItems: 'stretch', flexDirection: 'column' },
  },
  sectionLabel: {
    display: 'block',
    marginBottom: tokens.spacingVerticalS,
    color: tokens.colorPaletteDarkOrangeForeground1,
    textTransform: 'uppercase',
    fontWeight: tokens.fontWeightSemibold,
  },
  title: {
    display: 'block',
    fontSize: '42px',
    lineHeight: '48px',
    fontWeight: tokens.fontWeightSemibold,
  },
  lede: {
    display: 'block',
    maxWidth: '610px',
    marginTop: tokens.spacingVerticalM,
    color: tokens.colorNeutralForeground2,
    lineHeight: tokens.lineHeightBase400,
  },
  scenarioField: {
    minWidth: '220px',
    display: 'grid',
    rowGap: tokens.spacingVerticalXS,
  },
  workspace: {
    padding: '0 5vw 64px',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(260px, 320px)',
    gap: tokens.spacingHorizontalXXL,
    '@media (max-width: 820px)': { gridTemplateColumns: '1fr' },
  },
  queuePanel: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderTop: `3px solid ${tokens.colorBrandStroke1}`,
    boxShadow: tokens.shadow4,
  },
  activityPanel: {
    padding: tokens.spacingHorizontalXL,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTop: `3px solid ${tokens.colorPaletteDarkOrangeBorderActive}`,
    boxShadow: tokens.shadow4,
  },
  panelHeading: {
    minHeight: '72px',
    padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalL}`,
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalM,
    borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    '@media (max-width: 520px)': { alignItems: 'flex-start', flexWrap: 'wrap' },
  },
  panelTitle: { fontSize: tokens.fontSizeBase500, fontWeight: tokens.fontWeightSemibold },
  queueCount: { marginLeft: 'auto', color: tokens.colorNeutralForeground3 },
  queueState: {
    minHeight: '310px',
    padding: tokens.spacingHorizontalL,
    display: 'grid',
    alignContent: 'center',
  },
  requestList: { display: 'grid', gap: tokens.spacingVerticalS, alignSelf: 'start' },
  requestCard: {
    minHeight: '94px',
    display: 'grid',
    gridTemplateColumns: 'minmax(150px, 1fr) minmax(210px, 1.5fr) auto auto',
    alignItems: 'center',
    columnGap: tokens.spacingHorizontalXL,
    borderLeft: `4px solid ${tokens.colorPaletteDarkOrangeBorderActive}`,
    '@media (max-width: 820px)': { gridTemplateColumns: '1fr auto' },
    '@media (max-width: 520px)': { gridTemplateColumns: '1fr' },
  },
  requestIdentity: { display: 'grid', rowGap: tokens.spacingVerticalXXS },
  eyebrow: {
    color: tokens.colorPaletteDarkOrangeForeground1,
    textTransform: 'uppercase',
    fontWeight: tokens.fontWeightSemibold,
  },
  requestMeta: {
    margin: '0',
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    gap: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalM}`,
    '@media (max-width: 820px)': { gridColumn: '1 / -1' },
    '@media (max-width: 520px)': { gridColumn: 'auto' },
  },
  metaTerm: { color: tokens.colorNeutralForeground3 },
  metaValue: { margin: '0', fontWeight: tokens.fontWeightSemibold },
  stateCenter: {
    justifyItems: 'center',
    textAlign: 'center',
    rowGap: tokens.spacingVerticalM,
  },
  stateCopy: { maxWidth: '480px', color: tokens.colorNeutralForeground2 },
  activityTitle: { display: 'block', marginBottom: tokens.spacingVerticalL },
  correlation: {
    paddingTop: tokens.spacingVerticalM,
    paddingBottom: tokens.spacingVerticalM,
    display: 'grid',
    gap: tokens.spacingVerticalXS,
    borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
  },
  code: { overflowWrap: 'anywhere', color: tokens.colorBrandForeground1 },
  timeline: { marginTop: tokens.spacingVerticalL, paddingLeft: tokens.spacingHorizontalL },
  timelineItem: { paddingBottom: tokens.spacingVerticalL },
  timelineDetail: {
    display: 'block',
    marginTop: tokens.spacingVerticalXS,
    color: tokens.colorNeutralForeground3,
  },
  mobileAction: { '@media (max-width: 520px)': { width: '100%' } },
});
